### ISSUE TITLE
miniscopecotroller spopntaneously shut down

### ISSUE THREAD

**Issue by zeit0062** [daharoni/Miniscope_DAQ_Software#18]
the interface of miniscopecotroller spopntaneously shut down, when i clik on the "connect" botton of behaviorCam in the miniscopecontrol

**Comment by daharoni** [comment]
Please switch over to our newer Miniscope software (https://github.com/Aharoni-Lab/Miniscope-DAQ-QT-Software) and firmware (https://github.com/Aharoni-Lab/Miniscope-DAQ-Cypress-firmware).
