### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by DenisPolygalov** [daharoni/Miniscope_DAQ_Software#5]
https://choosealicense.com/no-license/
Absence of license file means no one else can use this code/software without being at risk of dealing with lawyers. 
"If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose."

**Comment by jonnew** [comment]
This is a very important issue to facilitate open source development. All the UCLA miniscope repos need a license to ensure the hard work of the UCLA team is respected and to clarify if 3rd party modifications can be distributed.

**Comment by daharoni** [comment]
Updated project with the MIT license.
